// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWfoalALRkNBAq6-bA1kHByimnwxOj3rA',
    appId: '1:249136816950:web:6ca24c1bc40f1f87b94997',
    messagingSenderId: '249136816950',
    projectId: 'travelapp-f2064',
    authDomain: 'travelapp-f2064.firebaseapp.com',
    storageBucket: 'travelapp-f2064.appspot.com',
    measurementId: 'G-MR5QEEEZH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0kjVL7Oej5f-NaIwE7rkgIdjlT4SOy0c',
    appId: '1:249136816950:android:e81b2568f4492a4eb94997',
    messagingSenderId: '249136816950',
    projectId: 'travelapp-f2064',
    storageBucket: 'travelapp-f2064.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXu3DSpFv9R8BC0lWKU0FmwuN44-9PNxg',
    appId: '1:249136816950:ios:67766bd876ffc1b2b94997',
    messagingSenderId: '249136816950',
    projectId: 'travelapp-f2064',
    storageBucket: 'travelapp-f2064.appspot.com',
    iosClientId: '249136816950-580n2v6omd8evb6hl8nj5jhob54va2lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXu3DSpFv9R8BC0lWKU0FmwuN44-9PNxg',
    appId: '1:249136816950:ios:67766bd876ffc1b2b94997',
    messagingSenderId: '249136816950',
    projectId: 'travelapp-f2064',
    storageBucket: 'travelapp-f2064.appspot.com',
    iosClientId: '249136816950-580n2v6omd8evb6hl8nj5jhob54va2lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );
}
